version: '2'
services:
  app-services:
    build: ./services
    ports:
      - "8090:8090"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  app-interfaces:
    build: ./interfaces/build
    ports:
      - "8010:8080"